spring.application.name=embabel_tutorial

# Embabel
embabel.agent.platform.models.openai.api-key=sk-proj-WcKH0qrYGPdC5-dF0q0c1tjJRb-BxgfGnsL0VnhtRbxZ27_vWTcL08caK71lwI4SnnJ_E

# Embabel models
embabel.models.default-llm=gpt-4o-mini
embabel.models.llms.reviewer=gpt-4o-mini
